### ISSUE TITLE
device_key is missing in Mariko/OLED's prod.keys

### ISSUE THREAD

**Issue by death7lord** [Thealexbarney/LibHac#295] opened 2023-12-28 17:41 UTC
Hello.
Description of hactoolnet : "Save data options: --sign Sign the save file. (Requires device_key in key file)".
My prod.keys from OLED contains "device_key_4x" only.
hactoolnet shows error: "Unable to sign save file. Do you have all the required keys?"
How and where do I can get device_key of my OLED?

I wanna replace/transfer file rawnand.bin/SYSTEM/save/80000000000000f0/PlayEvent.dat from 1st rev Unpatched to OLED model.
I have backup saves via DBI. And user profile backub via Linkalho. Now I want transfer a log of played time and launched titles log.

**Comment by Thealexbarney** [comment] 2024-05-19 04:11
Duplicate of #267

**Closed by Thealexbarney** 2024-05-19 04:11 UTC
