### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lsp199308** [Thealexbarney/LibHac#275] opened 2023-06-17 12:39 UTC
Hello, I have a mariko device and I follow this guide https://gbatemp.net/threads/how-to-skip-the-connect-joycons-system-init-screen.559745/, however, when I use the signature save LibHac0.18.0 prompts an error, I use lockpick_Rcm1.9.10 and I have dumped prod.keys, thanks，I checked prod.keys and I'm sure I already have the required keys

![image](https://github.com/Thealexbarney/LibHac/assets/77911322/af42980d-f885-438e-8790-478d9dfab2e2)

This may be a bug

hactoolnet(0.18.0), when I use hactoolnet -t save -k prod.keys 80000000000000000050 --replacefile file (***), hactoolnet prompts that it does not have the required key file and cannot sign and save. hactoolnet 0.13.0 does not have any errors, it can sign and save

**Comment by Thealexbarney** [comment] 2024-05-19 04:11
Duplicate of #267

**Closed by Thealexbarney** 2024-05-19 04:11 UTC
